spring:
  datasource:
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://localhost:3306/primeton_test?characterEncoding=utf-8
   username: root
   password: 123213


mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.primeton.ygq.demo.dao


logging:
  config: classpath:logback.xml
  level:
    com.simons.cn.springbootdemo.dao.system:
       debug

server:
  port: 12277

swagger:
  basePackage: com.primeton.ygq.demo
  title: 用户服务
  description: 用户基本增删改查
  version: V1.0
